/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projeto.gradle.josealfredo;

public class Library {
    public boolean someLibraryMethod() {
        return true;
        
    }
}
